onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /ipbus_i2c_master_tb/clk
add wave -noupdate /ipbus_i2c_master_tb/rst
add wave -noupdate /ipbus_i2c_master_tb/ipbus_in
add wave -noupdate /ipbus_i2c_master_tb/ipbus_out
add wave -noupdate /ipbus_i2c_master_tb/ipbus_in_fast
add wave -noupdate /ipbus_i2c_master_tb/ipbus_out_fast
add wave -noupdate /ipbus_i2c_master_tb/ipbus_in_mem
add wave -noupdate /ipbus_i2c_master_tb/ipbus_out_mem
add wave -noupdate /ipbus_i2c_master_tb/scl_o
add wave -noupdate /ipbus_i2c_master_tb/scl_i
add wave -noupdate /ipbus_i2c_master_tb/sda_o
add wave -noupdate /ipbus_i2c_master_tb/sda_i
add wave -noupdate /ipbus_i2c_master_tb/dut/stb
add wave -noupdate /ipbus_i2c_master_tb/dut/stb_x
add wave -noupdate /ipbus_i2c_master_tb/dut/ack
add wave -noupdate /ipbus_i2c_master_tb/dut/ack_last
add wave -noupdate /ipbus_i2c_master_tb/dut/addr
add wave -noupdate /ipbus_i2c_master_tb/dut/data_in
add wave -noupdate /ipbus_i2c_master_tb/dut/data_out
add wave -noupdate /ipbus_i2c_master_tb/dut/we
add wave -noupdate /ipbus_i2c_master_tb/dut/sr
add wave -noupdate /ipbus_i2c_master_tb/dut/state
add wave -noupdate /ipbus_i2c_master_tb/dut/statenext
add wave -noupdate /ipbus_i2c_master_tb/dut/devaddr
add wave -noupdate /ipbus_i2c_master_tb/dut/busaddr
add wave -noupdate /ipbus_i2c_master_tb/dut/ackseen
add wave -noupdate /ipbus_i2c_master_tb/dut/tipseen
add wave -noupdate /ipbus_i2c_master_tb/dut/bytecount
add wave -noupdate /ipbus_i2c_master_tb/dut/i2c/prer
add wave -noupdate /ipbus_i2c_master_tb/dut/i2c/ctr
add wave -noupdate /ipbus_i2c_master_tb/dut/i2c/txr
add wave -noupdate /ipbus_i2c_master_tb/dut/i2c/rxr
add wave -noupdate /ipbus_i2c_master_tb/dut/i2c/cr
add wave -noupdate /ipbus_i2c_master_tb/dut/i2c/done
add wave -noupdate /ipbus_i2c_master_tb/dut/i2c/core_en
add wave -noupdate /ipbus_i2c_master_tb/dut/i2c/ien
add wave -noupdate /ipbus_i2c_master_tb/dut/i2c/irxack
add wave -noupdate /ipbus_i2c_master_tb/dut/i2c/irq_flag
add wave -noupdate /ipbus_i2c_master_tb/dut/i2c/i2c_busy
add wave -noupdate /ipbus_i2c_master_tb/dut/i2c/i2c_al
add wave -noupdate /ipbus_i2c_master_tb/dut/i2c/core_cmd
add wave -noupdate /ipbus_i2c_master_tb/dut/i2c/core_txd
add wave -noupdate /ipbus_i2c_master_tb/dut/i2c/core_ack
add wave -noupdate /ipbus_i2c_master_tb/dut/i2c/core_rxd
add wave -noupdate /ipbus_i2c_master_tb/dut/i2c/rst_i
add wave -noupdate /ipbus_i2c_master_tb/dut/i2c/sta
add wave -noupdate /ipbus_i2c_master_tb/dut/i2c/sto
add wave -noupdate /ipbus_i2c_master_tb/dut/i2c/rd
add wave -noupdate /ipbus_i2c_master_tb/dut/i2c/wr
add wave -noupdate /ipbus_i2c_master_tb/dut/i2c/ack
add wave -noupdate /ipbus_i2c_master_tb/dut/i2c/iack
add wave -noupdate /ipbus_i2c_master_tb/dut/i2c/wb_ack_o_int
add wave -noupdate /ipbus_i2c_master_tb/dut/i2c/wb_wacc
add wave -noupdate /ipbus_i2c_master_tb/dut/i2c/acki
add wave -noupdate /ipbus_i2c_master_tb/dut/i2c/byte_controller/c_state
add wave -noupdate /ipbus_i2c_master_tb/dut/i2c/byte_controller/go
add wave -noupdate /ipbus_i2c_master_tb/dut/i2c/byte_controller/dcnt
add wave -noupdate /ipbus_i2c_master_tb/dut/i2c/byte_controller/cnt_done
add wave -noupdate /ipbus_i2c_master_tb/dut/i2c/byte_controller/sr
add wave -noupdate /ipbus_i2c_master_tb/dut/i2c/byte_controller/shift
add wave -noupdate /ipbus_i2c_master_tb/dut/i2c/byte_controller/ld
add wave -noupdate /ipbus_i2c_master_tb/dut/i2c/byte_controller/cmd_ack_int
add wave -noupdate /ipbus_i2c_master_tb/dut/i2c/bit_controller/sSCL
add wave -noupdate /ipbus_i2c_master_tb/dut/i2c/bit_controller/sSDA
add wave -noupdate /ipbus_i2c_master_tb/dut/i2c/bit_controller/dscl_oen
add wave -noupdate /ipbus_i2c_master_tb/dut/i2c/bit_controller/sda_chk
add wave -noupdate /ipbus_i2c_master_tb/dut/i2c/bit_controller/clk_en
add wave -noupdate /ipbus_i2c_master_tb/dut/i2c/bit_controller/slave_wait
add wave -noupdate /ipbus_i2c_master_tb/dut/i2c/bit_controller/dSCL
add wave -noupdate /ipbus_i2c_master_tb/dut/i2c/bit_controller/dSDA
add wave -noupdate /ipbus_i2c_master_tb/dut/i2c/bit_controller/sta_condition
add wave -noupdate /ipbus_i2c_master_tb/dut/i2c/bit_controller/sto_condition
add wave -noupdate /ipbus_i2c_master_tb/dut/i2c/bit_controller/cmd_stop
add wave -noupdate /ipbus_i2c_master_tb/dut/i2c/bit_controller/cnt
add wave -noupdate /ipbus_i2c_master_tb/dut/i2c/bit_controller/scl_oen_int
add wave -noupdate /ipbus_i2c_master_tb/dut/i2c/bit_controller/sda_oen_int
add wave -noupdate /ipbus_i2c_master_tb/dut/i2c/bit_controller/busy_int
add wave -noupdate /ipbus_i2c_master_tb/dut/i2c/bit_controller/al_int
add wave -noupdate /ipbus_i2c_master_tb/dut/i2c/bit_controller/c_state
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {4831789 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 450
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {4617816 ps} {4992202 ps}
