
CABLE=DE5

IPs = \
    $(wildcard a10/ddr/ddr3_if.tcl) \
    $(wildcard a10/ddr/ddr4_if.tcl) \
    $(wildcard a10/ip/*.tcl) \
    $(wildcard a10/pcieapp/*.tcl) \
    $(wildcard a10/*.vhd.envsubst) \
    nios.tcl

include util/quartus/makefile.mk
