
CABLE=DE5

IPs = \
    $(wildcard a10/ddr/ddr3/*.tcl) \
    $(wildcard a10/ip/*.tcl) \
    $(wildcard a10/pcieapp/*.tcl) \
    $(wildcard a10/*.vhd.envsubst) \
    nios.tcl

include util/altera/makefile.mk
