
// setup for cosmic run 2022
uint32_t scifi_num_asics = 8;
uint32_t scifi_num_modules_per_feb = 1;
uint32_t scifi_num_asics_per_module = 4;
uint32_t nasics_scifi = scifi_num_modules_per_feb * scifi_num_asics_per_module * 2;

uint32_t tile_num_asics = 0;
uint32_t tile_num_modules_per_feb = 0;
uint32_t tile_num_asics_per_module = 0;
uint32_t nasics_tile = tile_num_modules_per_feb * tile_num_asics_per_module * 0;