#

set module_name gtx_reset_firefly
set dir .cache/

create_ip -vlnv xilinx.com:ip:gtwizard:3.6 \
          -module_name $module_name -dir $dir

set_property -dict [ list \
    {CONFIG.gt0_uselabtools} {true} \
    {CONFIG.gt0_usesharedlogic} {1} \
    {CONFIG.gt0_val} {false} \
    {CONFIG.gt0_val_chan_bond_seq_1_1} {01111100} \
    {CONFIG.gt0_val_chan_bond_seq_1_1_k} {true} \
    {CONFIG.gt0_val_chan_bond_seq_1_2_mask} {true} \
    {CONFIG.gt0_val_chan_bond_seq_1_3_mask} {true} \
    {CONFIG.gt0_val_chan_bond_seq_1_4_mask} {true} \
    {CONFIG.gt0_val_clk_cor_seq_1_1} {00000000} \
    {CONFIG.gt0_val_clk_cor_seq_1_1_k} {true} \
    {CONFIG.gt0_val_clk_cor_seq_1_2} {00000000} \
    {CONFIG.gt0_val_clk_cor_seq_1_2_k} {true} \
    {CONFIG.gt0_val_clk_cor_seq_1_3} {00000000} \
    {CONFIG.gt0_val_clk_cor_seq_1_3_k} {true} \
    {CONFIG.gt0_val_clk_cor_seq_1_4} {00000000} \
    {CONFIG.gt0_val_clk_cor_seq_1_4_k} {true} \
    {CONFIG.gt0_val_clk_cor_seq_2_1} {00000000} \
    {CONFIG.gt0_val_clk_cor_seq_2_2} {00000000} \
    {CONFIG.gt0_val_clk_cor_seq_2_3} {00000000} \
    {CONFIG.gt0_val_clk_cor_seq_2_4} {00000000} \
    {CONFIG.gt0_val_comma_preset} {K28.5} \
    {CONFIG.gt0_val_cpll_rxout_div} {4} \
    {CONFIG.gt0_val_cpll_txout_div} {4} \
    {CONFIG.gt0_val_decoding} {8B/10B} \
    {CONFIG.gt0_val_dfe_mode} {LPM-Auto} \
    {CONFIG.gt0_val_drp_clock} {31.25} \
    {CONFIG.gt0_val_encoding} {8B/10B} \
    {CONFIG.gt0_val_no_rx} {true} \
    {CONFIG.gt0_val_pd_trans_time_non_p2} {25} \
    {CONFIG.gt0_val_port_loopback} {true} \
    {CONFIG.gt0_val_port_rxbufreset} {true} \
    {CONFIG.gt0_val_port_rxbufstatus} {true} \
    {CONFIG.gt0_val_port_rxdfereset} {false} \
    {CONFIG.gt0_val_port_rxpcsreset} {true} \
    {CONFIG.gt0_val_port_rxpmareset} {false} \
    {CONFIG.gt0_val_port_rxpowerdown} {true} \
    {CONFIG.gt0_val_port_rxslide} {false} \
    {CONFIG.gt0_val_port_txbufstatus} {true} \
    {CONFIG.gt0_val_port_txchardispmode} {true} \
    {CONFIG.gt0_val_port_txchardispval} {true} \
    {CONFIG.gt0_val_port_txpcsreset} {true} \
    {CONFIG.gt0_val_port_txpmareset} {true} \
    {CONFIG.gt0_val_port_txpolarity} {true} \
    {CONFIG.gt0_val_port_txpowerdown} {true} \
    {CONFIG.gt0_val_port_txprbsforceerr} {true} \
    {CONFIG.gt0_val_port_txprbssel} {true} \
    {CONFIG.gt0_val_prbs_detector} {true} \
    {CONFIG.gt0_val_protocol_file} {aurora_8b10b_multi_lane_4byte} \
    {CONFIG.gt0_val_qpll_fbdiv} {40} \
    {CONFIG.gt0_val_rx_data_width} {32} \
    {CONFIG.gt0_val_rx_int_datawidth} {40} \
    {CONFIG.gt0_val_rx_line_rate} {1.25} \
    {CONFIG.gt0_val_rx_reference_clock} {125.000} \
    {CONFIG.gt0_val_rx_termination_voltage} {GND} \
    {CONFIG.gt0_val_rxslide_mode} {OFF} \
    {CONFIG.gt0_val_tx_buffer_bypass_mode} {Manual} \
    {CONFIG.gt0_val_tx_data_width} {32} \
    {CONFIG.gt0_val_tx_int_datawidth} {40} \
    {CONFIG.gt0_val_tx_line_rate} {1.25} \
    {CONFIG.gt0_val_tx_reference_clock} {125.000} \
    {CONFIG.gt0_val_txbuf_en} {false} \
    {CONFIG.gt0_val_txdiffctrl} {true} \
    {CONFIG.gt0_val_txmaincursor} {true} \
    {CONFIG.gt0_val_txoutclk_source} {true} \
    {CONFIG.gt0_val_txpostcursor} {true} \
    {CONFIG.gt0_val_txprecursor} {true} \
    {CONFIG.gt2_val} {true} \
    {CONFIG.gt2_val_rx_refclk} {REFCLK0_Q1} \
    {CONFIG.gt2_val_tx_refclk} {REFCLK0_Q1} \
    {CONFIG.gt3_val} {true} \
    {CONFIG.gt3_val_rx_refclk} {REFCLK0_Q1} \
    {CONFIG.gt3_val_tx_refclk} {REFCLK0_Q1} \
    {CONFIG.gt4_val} {true} \
    {CONFIG.gt4_val_rx_refclk} {REFCLK0_Q1} \
    {CONFIG.gt4_val_tx_refclk} {REFCLK0_Q1} \
    {CONFIG.gt5_val} {true} \
    {CONFIG.gt5_val_rx_refclk} {REFCLK0_Q1} \
    {CONFIG.gt5_val_tx_refclk} {REFCLK0_Q1} \
    {CONFIG.gt6_val} {true} \
    {CONFIG.gt6_val_rx_refclk} {REFCLK0_Q1} \
    {CONFIG.gt6_val_tx_refclk} {REFCLK0_Q1} \
    {CONFIG.gt7_val} {true} \
    {CONFIG.gt7_val_rx_refclk} {REFCLK0_Q1} \
    {CONFIG.gt7_val_tx_refclk} {REFCLK0_Q1} \
    {CONFIG.gt8_val} {true} \
    {CONFIG.gt8_val_rx_refclk} {REFCLK0_Q1} \
    {CONFIG.gt8_val_tx_refclk} {REFCLK0_Q1} \
    {CONFIG.gt9_val} {true} \
    {CONFIG.gt9_val_rx_refclk} {REFCLK0_Q1} \
    {CONFIG.gt9_val_tx_refclk} {REFCLK0_Q1} \
    {CONFIG.gt_val_drp_clock} {100} \
    {CONFIG.identical_protocol_file} {aurora_8b10b_multi_lane_4byte} \
    {CONFIG.identical_val_no_rx} {true} \
    {CONFIG.identical_val_rx_line_rate} {1.25} \
    {CONFIG.identical_val_rx_reference_clock} {125.000} \
    {CONFIG.identical_val_tx_line_rate} {1.25} \
    {CONFIG.identical_val_tx_reference_clock} {125.000} \
] [ get_ips $module_name ]
