odbedit -d /Equipment/PixelsCentral/QCTests/Ladder/LINKQUALIcheck/Output/0/Scan -c "create DOUBLE VPVCO[30]" 
odbedit -d /Equipment/PixelsCentral/QCTests/Ladder/LINKQUALIcheck/Output/0/Scan -c "create DOUBLE error_rate[30]" 
odbedit -d /Equipment/PixelsCentral/QCTests/Ladder/LINKQUALIcheck/Output/1/Scan -c "create DOUBLE VPVCO[30]" 
odbedit -d /Equipment/PixelsCentral/QCTests/Ladder/LINKQUALIcheck/Output/1/Scan -c "create DOUBLE error_rate[30]" 
odbedit -d /Equipment/PixelsCentral/QCTests/Ladder/LINKQUALIcheck/Output/2/Scan -c "create DOUBLE VPVCO[30]" 
odbedit -d /Equipment/PixelsCentral/QCTests/Ladder/LINKQUALIcheck/Output/2/Scan -c "create DOUBLE error_rate[30]" 

odbedit -d /Equipment/PixelsCentral/QCTests/Ladder/LINKQUALIcheck/Output/0/Scan -c "create DOUBLE error_rate_linkA[30]" 
odbedit -d /Equipment/PixelsCentral/QCTests/Ladder/LINKQUALIcheck/Output/0/Scan -c "create DOUBLE error_rate_linkB[30]" 
odbedit -d /Equipment/PixelsCentral/QCTests/Ladder/LINKQUALIcheck/Output/0/Scan -c "create DOUBLE error_rate_linkC[30]" 
odbedit -d /Equipment/PixelsCentral/QCTests/Ladder/LINKQUALIcheck/Output/1/Scan -c "create DOUBLE error_rate_linkA[30]" 
odbedit -d /Equipment/PixelsCentral/QCTests/Ladder/LINKQUALIcheck/Output/1/Scan -c "create DOUBLE error_rate_linkB[30]" 
odbedit -d /Equipment/PixelsCentral/QCTests/Ladder/LINKQUALIcheck/Output/1/Scan -c "create DOUBLE error_rate_linkC[30]" 
odbedit -d /Equipment/PixelsCentral/QCTests/Ladder/LINKQUALIcheck/Output/2/Scan -c "create DOUBLE error_rate_linkA[30]" 
odbedit -d /Equipment/PixelsCentral/QCTests/Ladder/LINKQUALIcheck/Output/2/Scan -c "create DOUBLE error_rate_linkB[30]" 
odbedit -d /Equipment/PixelsCentral/QCTests/Ladder/LINKQUALIcheck/Output/2/Scan -c "create DOUBLE error_rate_linkC[30]" 
