/************************************************
* Register map header file 
* Automatically generated from /home/labor/Desktop/daq/library/mudaq/../../firmware/pcie/source/mudaq_registers.vhd
* On 2019-05-10T17:36:46.897278
************************************************/

#ifndef MUDAQ_REGISTERS__H 
#define MUDAQ_REGISTERS__H 


#define LED_REGISTER_W		0x00
#define RESET_REGISTER_W		0x01
#define RESET_BIT_ALL		0
#define GET_RESET_BIT_ALL(REG) ((REG>>0)& 0x1) 
#define SET_RESET_BIT_ALL(REG) ((1<<0)| REG) 
#define UNSET_RESET_BIT_ALL(REG) ((~(1<<0)) & REG) 
#define RESET_BIT_DATAGEN		1
#define GET_RESET_BIT_DATAGEN(REG) ((REG>>1)& 0x1) 
#define SET_RESET_BIT_DATAGEN(REG) ((1<<1)| REG) 
#define UNSET_RESET_BIT_DATAGEN(REG) ((~(1<<1)) & REG) 
#define RESET_BIT_PCIE		31
#define GET_RESET_BIT_PCIE(REG) ((REG>>31)& 0x1) 
#define SET_RESET_BIT_PCIE(REG) ((1<<31)| REG) 
#define UNSET_RESET_BIT_PCIE(REG) ((~(1<<31)) & REG) 
#define DATAGENERATOR_REGISTER_W		0x02
#define DATAGENERATOR_BIT_ENABLE		0
#define GET_DATAGENERATOR_BIT_ENABLE(REG) ((REG>>0)& 0x1) 
#define SET_DATAGENERATOR_BIT_ENABLE(REG) ((1<<0)| REG) 
#define UNSET_DATAGENERATOR_BIT_ENABLE(REG) ((~(1<<0)) & REG) 
#define DATAGENERATOR_BIT_ENABLE_PIXEL		1
#define GET_DATAGENERATOR_BIT_ENABLE_PIXEL(REG) ((REG>>1)& 0x1) 
#define SET_DATAGENERATOR_BIT_ENABLE_PIXEL(REG) ((1<<1)| REG) 
#define UNSET_DATAGENERATOR_BIT_ENABLE_PIXEL(REG) ((~(1<<1)) & REG) 
#define DATAGENERATOR_BIT_ENABLE_FIBRE		2
#define GET_DATAGENERATOR_BIT_ENABLE_FIBRE(REG) ((REG>>2)& 0x1) 
#define SET_DATAGENERATOR_BIT_ENABLE_FIBRE(REG) ((1<<2)| REG) 
#define UNSET_DATAGENERATOR_BIT_ENABLE_FIBRE(REG) ((~(1<<2)) & REG) 
#define DATAGENERATOR_BIT_ENABLE_TILE		3
#define GET_DATAGENERATOR_BIT_ENABLE_TILE(REG) ((REG>>3)& 0x1) 
#define SET_DATAGENERATOR_BIT_ENABLE_TILE(REG) ((1<<3)| REG) 
#define UNSET_DATAGENERATOR_BIT_ENABLE_TILE(REG) ((~(1<<3)) & REG) 
#define DATAGENERATOR_NPIXEL_RANGE_HI		15
#define DATAGENERATOR_NPIXEL_RANGE_LOW		8
#define GET_DATAGENERATOR_NPIXEL_RANGE(REG) ((REG>>8)&0xff) 
#define SET_DATAGENERATOR_NPIXEL_RANGE(REG, VAL) ((REG & (~(0xff<< 8))) | ((VAL & 0xff)<< 8))  
#define DATAGENERATOR_NFIBRE_RANGE_HI		23
#define DATAGENERATOR_NFIBRE_RANGE_LOW		16
#define GET_DATAGENERATOR_NFIBRE_RANGE(REG) ((REG>>16)&0xff) 
#define SET_DATAGENERATOR_NFIBRE_RANGE(REG, VAL) ((REG & (~(0xff<< 16))) | ((VAL & 0xff)<< 16))  
#define DATAGENERATOR_NTILE_RANGE_HI		31
#define DATAGENERATOR_NTILE_RANGE_LOW		24
#define GET_DATAGENERATOR_NTILE_RANGE(REG) ((REG>>24)&0xff) 
#define SET_DATAGENERATOR_NTILE_RANGE(REG, VAL) ((REG & (~(0xff<< 24))) | ((VAL & 0xff)<< 24))  
#define DATAGENERATOR_DIVIDER_REGISTER_W		0x03
#define DMA_REGISTER_W		0x38
#define DMA_BIT_ENABLE		0
#define GET_DMA_BIT_ENABLE(REG) ((REG>>0)& 0x1) 
#define SET_DMA_BIT_ENABLE(REG) ((1<<0)| REG) 
#define UNSET_DMA_BIT_ENABLE(REG) ((~(1<<0)) & REG) 
#define DMA_BIT_NOW		1
#define GET_DMA_BIT_NOW(REG) ((REG>>1)& 0x1) 
#define SET_DMA_BIT_NOW(REG) ((1<<1)| REG) 
#define UNSET_DMA_BIT_NOW(REG) ((~(1<<1)) & REG) 
#define DMA_CTRL_ADDR_LOW_REGISTER_W		0x39
#define DMA_CTRL_ADDR_HI_REGISTER_W		0x3a
#define DMA_DATA_ADDR_LOW_REGISTER_W		0x3b
#define DMA_DATA_ADDR_HI_REGISTER_W		0x3c
#define DMA_RAM_LOCATION_NUM_PAGES_REGISTER_W		0x3d
#define DMA_RAM_LOCATION_RANGE_HI		31
#define DMA_RAM_LOCATION_RANGE_LOW		20
#define GET_DMA_RAM_LOCATION_RANGE(REG) ((REG>>20)&0xfff) 
#define SET_DMA_RAM_LOCATION_RANGE(REG, VAL) ((REG & (~(0xfff<< 20))) | ((VAL & 0xfff)<< 20))  
#define DMA_NUM_PAGES_RANGE_HI		19
#define DMA_NUM_PAGES_RANGE_LOW		0
#define GET_DMA_NUM_PAGES_RANGE(REG) ((REG>>0)&0xfffff) 
#define SET_DMA_NUM_PAGES_RANGE(REG, VAL) ((REG & (~(0xfffff<< 0))) | ((VAL & 0xfffff)<< 0))  
#define DMA_NUM_ADDRESSES_REGISTER_W		0x3e
#define PLL_REGISTER_R		0x00
#define DIPSWITCH_RANGE_HI		7
#define DIPSWITCH_RANGE_LOW		0
#define GET_DIPSWITCH_RANGE(REG) ((REG>>0)&0xff) 
#define SET_DIPSWITCH_RANGE(REG, VAL) ((REG & (~(0xff<< 0))) | ((VAL & 0xff)<< 0))  
#define VERSION_REGISTER_R		0x01
#define VERSION_RANGE_HI		27
#define VERSION_RANGE_LOW		0
#define GET_VERSION_RANGE(REG) ((REG>>0)&0xfffffff) 
#define SET_VERSION_RANGE(REG, VAL) ((REG & (~(0xfffffff<< 0))) | ((VAL & 0xfffffff)<< 0))  
#define EVENTCOUNTER_REGISTER_R		0x02
#define TIMECOUNTER_LOW_REGISTER_R		0x03
#define TIMECOUNTER_HIGH_REGISTER_R		0x04
#define MEM_WRITEADDR_LOW_REGISTER_R		0x05
#define MEM_WRITEADDR_HIGH_REGISTER_R		0x06
#define DMA_STATUS_REGISTER_R		0x38
#define DMA_DATA_ADDR_LOW_REGISTER_R		0x39
#define DMA_DATA_ADDR_HI_REGISTER_R		0x3a
#define DMA_NUM_PAGES_REGISTER_R		0x3b


#endif  //#ifndef MUDAQ_REGISTERS__H 
